### PR TITLE
Flatten vote data and add a query around getting the votes for the week.

### PR DESCRIPTION
**Pull request by keathley**
I removed the extra nesting that we had around lunch votes.  I also added a real query around selecting only this weeks lunches (which is only possible with the new flatter data structure).

### CODE REVIEW

**Comment by jordanisip** [comment]
Awesome! Any idea how to migrate the prod data?

**Comment by keathley** [comment]
the easiest way to do it is probably to run a script that copies everything pushes it back up in the proper format, and then deletes the old stuff.

**Comment by jordanisip** [comment]
Cool, let's figure that out one of these hack nights. No huge rush since this should work with prod data and will only matter when we start querying for older data (when we setup some reporting UI).

**Comment by jordanisip** [comment]
Now deployed on http://git.io/vote

**Pull request merged**
